logging:
  level:
    root: info

server:
  ssl:
    enabled: false
  port: 2244

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:54321/db2_dev
    username: db2
    password: db2
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        default_schema: public
    hibernate:
      ddl-auto: update

rajdownik:
  auth:
    jwtSecret: 688dc1754ba81961938cee3adb5b1b68167c1cf5531f6da17490b550b6465fb8
  frontend-url: http://localhost:3000/