logging:
  level:
    root: info

server:
  ssl:
    enabled: false
  port: 2244

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        default_schema: public
    hibernate:
      ddl-auto: update

rajdownik:
  auth:
    jwtSecret: ${JWT_SECRET}
  frontend-url: ${FRONTEND_URL}